export const TypeAction = {
  STATUS_LOAD: 'STATUS_LOAD',
  PLUS_PROD: 'PLUS_PROD',
  MINUS_PROD: 'MINUS_PROD',
  TODOS_LOADED: 'TODOS_LOADED',
  ADD_CART: 'ADD_CART',
  UPDATE_QTY: 'UPDATE_QTY',
  LOAD_ITEM: 'LOAD_ITEM',
}
